server:
  port: 8771

spring:
  application:
    name: eurka-server
  profiles:
    active: eurekaServer1

eureka:
  instance:
    hostname: eurekaServer1
  #####prefer-ip-address: true #支持多个EurekaServer互相通过IP注册
  client:
    registerWithEureka: false  #说明自己是一个eurekaServer
    fetchRegistry: false #说明自己是一个eurekaServer
    serviceUrl:
      defaultZone: http://eurekaServer:8761/eureka/,http://eurekaServer2:8781/eureka/
  server:
    ###renewalPercentThreshold: 0.49
    #enable-self-preservation: false #关闭自我保护，会将关停的节点剔除
    eviction-interval-timer-in-ms: 600000 #清理关停服务间隔，默认60*1000毫秒

